### PR TITLE
Add duration preference type

### PR DESCRIPTION
**Pull request by rvignesh89**
@EliotBerriot based on our discussion in #8 I've added `DurationPreference` first as I might be needing this. Implementation was straightforward as I expected.

Could you take a look into it and see if it makes sense?

### CODE REVIEW

**Comment by rvignesh89** [comment]
Ah I didn't wait for the checks to pass the first time. They pass now :)

What I did here was to use `django.utils.duration.duration_string` which serializes timedelta into strings like below,

```
7 00:00:00  -> 1 week
00:01:00 -> 1 minute
```

I'd definitely prefer to serialize to ISO 8601 duration format. But having to add a library just to do makes me cringe a little. I like libraries which don't depend on other libraries to do simple things. Also considering that users of django-dynamic-preferences who are on Django 1.11(which is when duration_iso_string was introduced) can just create their own serializers and preference types which use the ISO format to serialize/deserialize records I think it makes sense to not import a library just to do this.

Another reason I chose `duration_string` was because thats currently being used in Django's `DurationField` for backward compatibility reasons I assume. So `duration_string` should be here to stay IMO.

**Comment by EliotBerriot** [comment]
I agree with you : avoiding extra dependencies is a plus, and using the built-in  `duration_string` is okay for me, even if less "clean" than serializing to iso.

Let's merge!

**Comment by rvignesh89** [comment]
Awesome! Appreciate your quick response 👍

**Comment by rvignesh89** [comment]
Is there any plan to release a new version with the above changes anytime soon? It would help to start using it.

**Comment by EliotBerriot** [comment]
I was actually waiting a few days to give you time to work on the two other date-related preferences, but I should have tell you, sorry!

I can probably publish a new release tonight or tomorrow, I'll keep you updated :)

**Comment by rvignesh89** [comment]
Ah alright. I thought it would better to add a separate PR for those two. I'll do that soon!

**Comment by EliotBerriot** [comment]
Yeah, it's fine to have separate PRs for that purpose, I just wanted to avoid doing multiple release, each one containing only a single change if possible.

**Pull request merged**
