### PR TITLE
Add Docs

### PR DESCRIPTION
**Pull request by JetUni**
Did this so we won't have another #51 and to satisfy #52

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Great, thanks!

**Comment by JetUni** [comment]
You're welcome! I just wanted to ask though, would you have any time to document more on here about how to use your own template for listing and changing the preferences? I still don't understand how to do that.... :confused: I looked at [this](https://django-dynamic-preferences.readthedocs.io/en/stable/quickstart.html#bundled-views-and-urls), but I'm unsure what to do with it and to be honest, it made me think that there's a view/template bundled with the app that will let me update the preferences and all I have to do is include the url, and then go to http://example.com/preferences/.

**Comment by EliotBerriot** [comment]
It's exactly that: if you include the URLs, you'll be able to edit the preferences (global and linked to your user account) via a dedicated set of views / templates instead of via the admin interface.

as you can see in the [`urls.py`](https://github.com/EliotBerriot/django-dynamic-preferences/blob/master/dynamic_preferences/urls.py) file, global preferences require a staff member to be logged in.
 
If you want to change [the templates](https://github.com/EliotBerriot/django-dynamic-preferences/tree/master/dynamic_preferences/templates/dynamic_preferences) used by these views, you have to override them using the regular django mechanism.

For example, let's say you want to override the template `dynamic_preferences/base.html`, and your own project templates are stored in a `templates` directory, you just need to create a `templates/dynamic_preferences/base.html` file, and it ill be used instead.

Does it answer your question ?

**Comment by JetUni** [comment]
Yeah, I guess it does. It's just weird though, because I tried this a while ago and it didn't work, but it is now for some reason!

**Comment by EliotBerriot** [comment]
Glad it helped, feel free to ask if you need anything else :)

**Comment by JetUni** [comment]
I actually do have one more question. I'm using the templates now and everything is working great, but I don't really want to make a new page for another setting that isn't part of my dynamic settings (it's a date which is why I'm not saving it in django-dynamic-preferences). So I'm wondering if there's a way to add data from one of my django apps to the form/view for that page?

**Comment by EliotBerriot** [comment]
My guess is it's possible, but it will be quite hackish (and very ugly). 

Let's say you're speaking a about user preferences. I think you'll have to:

1. Override the related view (`UserPreferenceFormView`), to provide a custom template
2. In this template, extends the previously declared template (`dynamic_preferences/form.html`), provide your own form markup, and add your missing field
3. In the overrided view, override the `post` method so that you can process the added field, either by passing the POST field to a dedicated form or by hand. Anyway, you'll have to call `super()` so `dynamic_preferences` form is handled as expected

Error handling will be a bit tricky because even if only one form is displayed to the user, there are in fact two forms from a django perspective.

**Comment by JetUni** [comment]
Yeah, that doesn't sound very pretty! I think I'll just stick with a Jquery AJAX function. Thx tho!

**Comment by JetUni** [comment]
Ok, I don't know if I should be submitting an issue about this, but for some reason the template that I made is working just fine on the dev environment that I have running locally, but as soon as I push it to GitHub and run it on our live server it doesn't save any of the preference values unless you're in the section for that preference.

Here is what I have:
`base.html`
``` html
{% extends base_template %}

{% block title %}
  Preferences
{% endblock %}


{% block main %}
  <div class="row">

    <div class="span1">
      <h3>Sections</h3>
      {% block sections %}{% endblock %}
    </div>
    <div class="span6 offset1">
      <h3>Preferences</h3>
      {% block content %}{% endblock %}
    </div>

    <div class="span4">
      <h3>Update</h3>
      <br />
      <a class="btn btn-medium btn-info" rel="tooltip"
       title="Update pricing on all bids that haven't been submitted"
       data-toggle="modal" data-target="#update-bids">
        <i class="icon-repeat"></i> Update Bids</a><br /><br />
      <a class="btn btn-medium btn-info" rel="tooltip"
       title="Update cache on all bids that haven't been submitted"
       data-toggle="modal" data-target="#update-cache">
        <i class="icon-repeat"></i> Update Cache</a>
    </div>

  </div>

  <div class="modal hide" id="update-bids">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">x</button>
      <h3>Update Bids</h3>
    </div>
    <div class="modal-body">
      <form method="POST" action="/bid/update_bid_pricing/">{% csrf_token %}
        <p>Text</p>
        <input class="btn btn-primary btn-large loadMaskIt" type="submit" value="Confirm" />
      </form>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    </div>
  </div>

  <div class="modal hide" id="update-cache">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">x</button>
      <h3>Update Cache</h3>
    </div>
    <div class="modal-body">
      <form method="POST" action="/bid/update_bid_cache/">{% csrf_token %}
        <p>Text</p>
        <input class="btn btn-primary btn-large loadMaskIt" type="submit" value="Confirm" />
      </form>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal">Cancel</a>
    </div>
  </div>

{% endblock %}
```

`form.html`
```
{% extends "dynamic_preferences/base.html" %}

{% block sections %}
  {% include "dynamic_preferences/sections.html" with sections=registry.sections %}
{% endblock %}

{% block content %}

  <form action="" enctype="multipart/form-data" method="post">{% csrf_token %}
    {% for setting in form %}
      {{ setting.label_tag }}
      <span rel="tooltip" title="{{ setting.help_text }}">{{ setting }}</span>
    {% endfor %}
    <br><br>
    <input class="btn btn-large btn-success" type="submit" value="Submit" />
  </form>
{% endblock %}
```

`sections.html`
```
<ul class="sections">
    {% for section in sections %}
        <li><a href="./{{ section }}">{{ section }}</a></li>
    {% endfor %}
</ul>
```

**Comment by EliotBerriot** [comment]
First, can you check that you are running the same versions of the package locally and an your live server ?  I made a release a few days ago and it may be a regression, explaining why it woul work locally but not on production.

Can you explain a bit more what you mean by `it doesn't save any of the preference values unless you're in the section for that preference.` ? You mean when you're visiting the URL for the section ?

Also, I realize some templates I wrote are kind of dirty, especially `<li><a href="./{{ section }}">{{ section }}</a></li>`, I should use django's `url` tag instead of doing that.

**Comment by JetUni** [comment]
They're both running on 0.8.1 which I've frozen in requirements.txt. I tried switching the live site to 0.8.2 and it still doesn't work. And yes, I mean that if you are on the `preferences/global/` page, it won't save any of the values, but if you go to one of the sections at `preferences/global/section_name/` and save the value, it will actually save. What is django's `url` tag in this case? I tried using `section.url` without any luck.

Also, is there any way that you could add something to the django form so that the user is aware that the form was submitted successfully? Something like a django message?

**Comment by JetUni** [comment]
Actually, it doesn't work on my local site when using 0.8.2 either. You can test this by changing a value and clicking submit, then clicking on the section for that value, after which it will change back to what it was before.

**Comment by EliotBerriot** [comment]
What you're saying about section form working but global form not working is interesting. I'll have to investigate and reproduce this in a test.

Regarding the message / feedback after the form submission, I'm afraid I won't implement such thing. The reason is that I don't think there is something generic enough to fit every use cases. Some projects will need a django message, others will need a redirection to a dedicated url, others will keep the same page but include a message in the template...

You can achieve this by subclassing the views yourself, override the `get_success_url` method and add the message here, for example.

**Comment by JetUni** [comment]
Alright, something like this?

``` python
class my_preferences_form(FormView, pref_views.PreferenceFormView):
    def get_success_url(self):
        messages.add_message(request, messages.SUCCESS, "Updated")
        HttpResponseRedirect(self.request.path)
```

**Comment by EliotBerriot** [comment]
yes, but you don't have to even inherit of FormView (i's already used by `PreferenceFormView`)

**Comment by JetUni** [comment]
Any updates on those tests?

**Comment by EliotBerriot** [comment]
Sorry, it has been quite a week. I'll try to free up some time tomorrow evening to work on this.

**Comment by JetUni** [comment]
No problem at all! I know what you mean! I'll be working on this on Thursday possibly so that would be awesome!

**Comment by EliotBerriot** [comment]
Im sorry, but I cannot reproduce this locally, neither in a test (see related commit) or using the example project.

Maybe there is something in your production setup that prevent this from working properly. Can you describe your setup more thoroughly, and maybe provide the POST requests/responses that occurs when you submit the form (when it works and when it does not). Ensure to include headers, requests paths, content, and so on.

**Pull request merged**
