### PR TITLE
Better user experience

### PR DESCRIPTION
**Pull request by n3storm**
Sections can have spaces, so they can be named like "CMS Posts"
Values can be unicode. In spanish "Read more" is written "Leer más". I allow my cms user to set this value as "Más" or "..." (etc) but default is "Leer más" and by default it was raising a exception.

Thanks for your module, is great!

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Thank you for the pull request and especially the UTF-8 fix !

For the spaces in sections names, I also accept your fix, but I don't feel comfortable having spaces in URLs, since it requires special encoding. When I designed sections, I thought of the section name as a slug, short identifier, not a verbose name that will be displayed to end users.

This is more a global issue/flaw in the section design (which is totally my bad) : Sections should probably be objects themselves, like:

    @sections.register
    class CMSPosts(Section):
        name = 'cms_post'
        verbose_name = _('CMS Posts')

This way, sections could handle internationalization using django tools, and we could probably use sections to manage common preferences behaviour.

I'll work on it as soon as possible.

**Comment by n3storm** [comment]
I completely agree Sections with your proposal, should I open a feature request issue?
Also I require a require = False (;-)) attribute for settings, maybe they already exists?

**Comment by EliotBerriot** [comment]
I've already opened an issue (#19) about that, feel free to contribute / discuss anything here.

>  Also I require a require = False (;-)) attribute for settings, maybe they already exists?

You mean settings with null value ? You can totally open an issue about that, I think it's already supported now, but I have to investigate and maybe to document the feature.

**Comment by n3storm** [comment]
I found this reading code! Thanks!

**Comment by n3storm** [comment]
This pull request should be rejected. My bad. Allowing spaces in section names breaks context_processor usage.
Alternatively we can use a templatetag to retrieve? or better go for proper section objects now?

Sorry sorry sorry

**Comment by EliotBerriot** [comment]
Oh, you're right. Fortunately, it has not been pushed to PyPi yet, so we can still fix this behaviour.

Section objects are the way to go, so if you really need this now and have no spare time, I can probably finish this for the end of the week :)

**Pull request merged**
