### PR TITLE
ModelMultipleChoicePreference

### PR DESCRIPTION
**Pull request by eriktelepovsky**
A feature of issue #143 

Also fixes issue #144

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Thank you! I'd like to have some tests for these new preferences, to ensure they work as intended and we don't have regressions in the future. Do you want to write those yourself, or do you prefer I write them?

You can get some inspiration here: https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/tests/test_types.py#L238

**Comment by EliotBerriot** [comment]
You can run tests with `tox -e py36-django-20` by the way :)

**Comment by eriktelepovsky** [comment]
Let me try :-)

**Comment by eriktelepovsky** [comment]
Can you check my TestModelSerializers class, please? Thanks.

**Pull request merged**
