### PR TITLE
Emit signal on preference update

### LINKED ISSUE #207: Emit signal on change of preference
I am currently trying to migrate the AlekSIS project from constance to django-dynamic-preferences. One missing part is that we need to invalidate a cache if one global preference is changed, so I'd like to have a signal emitted after update of a preference (much like the [setting_changed signal](https://docs.djangoproject.com/en/3.0/ref/signals/#setting-changed) in Django itself).

I looked into jsut using the `post_save` signal on `BasePreferenceModel`, but it does not allow to detect which preference was updated.

Another approach with a much smaller changeset would be to pass `section` and `name` as `update_fields` to the `save` call in the manager when saving the model, which will make its way through to the recipient of the `post_save` signal, but this does not look like "one obvious way" to me in terms of the Zen of Python.

I am willing to contribute this feature if the maintainer(s) do not generally object to it.

### PR DESCRIPTION
**Pull request by Natureshadow**
Closes #207.

### CODE REVIEW

**Comment by Natureshadow** [comment]
@EliotBerriot For some reason, I am unable to run tox on this project. I hope Travis will run for this PR… if not, maybe y cannot run it.

**Comment by EliotBerriot** [comment]
There seem to be an incompatibility between tox and pytest-sugar, I will fix this in a separate branch. Let's merge, thank you for working on this!

**Comment by Natureshadow** [comment]
Great, thanks! If you could release an updated version with this feature soon, this would help our free educational software a lot, as we also want to do a release during school closures in Germany and not ship with git dependencies :).

**Comment by EliotBerriot** [comment]
I cannot promise anything, but I'll try to have a look by next week

**Pull request merged**
