### PR TITLE
fix #85 - string serializer returning None

### LINKED ISSUE #85: Empty string in StringPreference serializes to 'None'
As in the title. I think it's because for some reason when the string preference is set to an empty string, it comes back from the db as `None`, which is then serialized as a string with `return str(value)`.

This basically makes it impossible to set an empty string in a StringPreference.

### PR DESCRIPTION
**Pull request by swalladge**

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Thanks for the PR, everything looks good to me, I'll merge when the CI checks are over :)

**Comment by swalladge** [comment]
Cool, no worries. Turned out to be a bit trivial for a PR, but anyway. :)

**Comment by swalladge** [comment]
By the way, I added `django-nose` to the test dependencies because the runtests.py script complained about it - not sure if I missed something and there was a reason django-nose wasn't included in `requirements-test.txt` before.

**Comment by EliotBerriot** [comment]
Okay, everything looks fine on my side, merge incoming!

**Comment by EliotBerriot** [comment]
1.3.1 was pushed to PyPi and includes this ;)

**Pull request merged**
