### PR TITLE
Propagate order of preferences through to forms

### PR DESCRIPTION
**Pull request by czlee**
In relation to #44, I think there's just one more change necessary to propagate the order through to the form :smile:

(Sorry if I got something wrong with the software architecture.)

### CODE REVIEW

**Comment by EliotBerriot** [comment]
God dammit, I forgot that! Thanks for the PR, I'll release this tomorrow :)

**Comment by EliotBerriot** [comment]
This is merged in 0.8.1 and pushed to PyPi, sorry for the delay!

**Comment by zbynekdrlik** [comment]
Dear @EliotBerriot I am still not sure how order is used in Admin integration and if I can reorder fields on listview page.

**Comment by EliotBerriot** [comment]
Hy @zbynekdrlik unfortunately this change doesn't apply to the admin. One thing you can do is replace [our admin module](https://github.com/EliotBerriot/django-dynamic-preferences/blob/develop/dynamic_preferences/admin.py#L67) by your own (but inheriting ours), then overload the `get_queryset` option to add an `order_by('section', 'name')` clause.

**Comment by zbynekdrlik** [comment]
Thanks it works. 
Here is example 
`    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).order_by('section', 'name')`

**Comment by zbynekdrlik** [comment]
@EliotBerriot I need exact sorting, not by name, but I need totally custom order of fields. Is it possible?
Every configuration on specific custom order.

**Comment by zbynekdrlik** [comment]
Dear @EliotBerriot I am trying something this:
```
    def get_queryset(self, *args, **kwargs):
        def exact_order(item):
            order_dict = {'plat_nazov1': 1, 'plat_nazov2': 2}
            if item.name in order_dict.keys():
                return order_dict[item.name]
            else:
                return 3
        qs = sorted(super().get_queryset(*args, **kwargs).all(), key=exact_order)
        return qs
```
qs is correctly sorted but admin page always give db error.

**Pull request merged**
