### PR TITLE
Fix crash: 'NoneType' object has no attribute 'name'

### PR DESCRIPTION
**Pull request by treemo**
https://github.com/EliotBerriot/django-dynamic-preferences/issues/163

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Thanks!

**Comment by zbynekdrlik** [comment]
when new version will be out?

**Comment by EliotBerriot** [comment]
I'm going to try to publish one this week

**Comment by EliotBerriot** [comment]
The 1.8 release with this change was pushed to PyPi: https://pypi.org/project/django-dynamic-preferences/1.8/

**Pull request merged**
