### PR TITLE
add django admin for user preferences

### PR DESCRIPTION
**Pull request by JanMalte**

### CODE REVIEW

**Comment by EliotBerriot** [comment]
Thank you for that, it was probably forgotten during the user app refactor. however, it seems your commit fails (see https://travis-ci.org/EliotBerriot/django-dynamic-preferences/jobs/230360724) for example. I suspect `admin.site.register` should be replaced with `admin.register`.

**Comment by JanMalte** [comment]
Thanks for the hint. I fixed it by importing the django admin package with a specific name

**Comment by EliotBerriot** [comment]
I've published a bugfix release (1.1.1) to PyPi including this.

**Comment by khankuan** [comment]
Awesome feature! @EliotBerriot are there documentation on how to enable it? I tried updating the package but did not see UserPreferences showing up in admin. Thanks!

**Comment by EliotBerriot** [comment]
@khankuan since version 1.0 you have to explicitely install the user app to benefits from user preferences. Have you followed the [upgrade instructions](https://django-dynamic-preferences.readthedocs.io/en/latest/upgrade.html#id1)? Where version where you upgrading from?

**Comment by khankuan** [comment]
I've added the 2 lines for settings. Is that sufficient or is there something I've missed?

**Comment by EliotBerriot** [comment]
This should be sufficient, assuming you also run `python manage.py migrate`. You still have nothing showing in the admin ?

**Pull request merged**
